# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.name = ''
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 525)
        self.id_label = QtWidgets.QLabel(Dialog)
        self.id_label.setGeometry(QtCore.QRect(200, 240, 400, 26))
        self.id_label.setObjectName("id_label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 280, 80, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.runscript)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 200, 80, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.file_open)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Convert"))
        self.pushButton_2.setText(_translate("Dialog", "Select file"))
        self.id_label.setText(_translate("Dialog", ""))

    def runscript(self):
        #print(subprocess.run('calibre-debug','temp.py','ABC.pdf','output.epub'))
        self.pushButton.setEnabled(False)
        subprocess.run(['calibre-debug','temp.py',self.name,'output.epub'])
        

        
    def file_open(self):
        self.name, _ = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', options=QtWidgets.QFileDialog.DontUseNativeDialog)
        self.id_label.setText(self.name)
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
